name: Release version

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  release-production:
    name: Release Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Push 'main' to 'production'
        uses: jojomatik/sync-branch@v1
        with:
          source: "main"
          target: "production"
          strategy: "rebase"
          github_token: ${{ secrets.GH_TOKEN }}
